// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mosha.StatePatter.Test.Db;

#nullable disable

namespace Mosha.StatePatter.Test.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Mosha.StatePatter.Test.Model.Deal.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DealerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Mosha.StatePatter.Test.Model.Deal.Deal", b =>
                {
                    b.OwnsOne("Mosha.StatePattern.StateBehavior<Mosha.StatePatter.Test.Model.Deal.States.Interface.IDealState, Mosha.StatePatter.Test.Model.Deal.Enums.DealStateEnum, Mosha.StatePatter.Test.Model.Deal.States.Rule.DealStateRule>", "State", b1 =>
                        {
                            b1.Property<int>("DealId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StateKey")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DealId");

                            b1.ToTable("Deals");

                            b1.WithOwner()
                                .HasForeignKey("DealId");
                        });

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
